class Administrator{

}
//addArtist(artistData)
//addAlbum(artistId, albumData)
//addTrack(albumId, trackData)
//getArtistById(id)
//getAlbumById(id)
//getTrackById(id)
//getPlaylistById(id)
//addUser(userData)
//getUserById(id)
//getUsers()
//getTracksMatchingGenres(genres)
//getTracksMatchingArtist(artistName)
//getArtists()
//getArtistByName(nameArtist)
//getTracks()
//getPlayLists()
//getAlbums()
//createPlaylist(name, genresToInclude, maxDuration)
//changeSearcher(aSearcher)
//searchTracksWithPartialName(partialStringToSearch)
//searchAlbumsWithPartialName(partialStringToSearch)
//searchArtistsWithPartialName(partialStringToSearch)
//searchPlaylistsWithPartialName(partialStringToSearch)
//searchByName(aName)
//userListenTrack(aUserID, aTrackID)
//timesUserListenedTrack(aUserID, aTrackID)
//top3TracksFromArtist(artistId)
